### PR TITLE
🧪 Use another Redis database for integration testing

### LINKED ISSUE #1035: Use another Redis database for integration testing
## Feature Description

Today we are using the same Redis database for testing and development.
We need to isolate environments to avoid unexpected behavior.

### PR DESCRIPTION
**Pull request by mateus4k**
## Summary

Resolves #1035

Today we are using the same Redis database for testing and development.
We need to isolate environments to avoid unexpected behavior.

## Checklist

- [x] My code passes the linting.
- [x] My code has proper inline documentation.
- [x] I have manually tested this PR.

### CODE REVIEW

File: packages/api/vowfile.js [hunk 1]
```diff
@@ -15,37 +15,24 @@ timeout(20 * 1000); // Set global timeout to 20sec
...
 			.close();
 
-		await ace.call('migration:reset', {}, { silent: true });
-		await fs.rmdir(Helpers.publicPath(uploadsPath), { recursive: true });
-		await fs.rmdir(Helpers.tmpPath('resources/test'), { recursive: true });
+		await Promise.all([
+			ace.call('migration:reset', {}, { silent: true }),
+			fs.rmdir(Helpers.publicPath(uploadsPath), { recursive: true }),
+			fs.rmdir(Helpers.tmpPath('resources/test'), { recursive: true }),
+			Redis.call('flushdb'),
```
Comment (mateus4k) [inline packages/api/vowfile.js:35]: Clean up the Redis database after the test is complete

Comment (mateus4k) [inline packages/api/vowfile.js:35]: Clean the Redis test database after running the tests

**Review by luizeboli — APPROVED** [review]
