### PR TITLE
API is not calling the right Algolia index on endpoints

### LINKED ISSUE #994: API is not deleting Algolia objects
## Feature Description

The object is not deleted, basically. When deleting, it is called a wrong index.

### PR DESCRIPTION
**Pull request by mateus4k**
## Summary

Resolves #994

## Checklist

- [x] My code passes the linting.
- [x] I have manually tested this PR.

### CODE REVIEW

**Comment by mateus4k** [comment]
Waiting for #981 to be merged before releasing for review

File: packages/api/app/Utils/Algolia/core.js [hunk 1]
```diff
@@ -2,11 +2,10 @@ const Config = use('Config');
 const AlgoliaSearch = use('App/Services/AlgoliaSearch');
 
 const config = Config.get('algolia');
-const getNestedValue = require('../getNestedValue');
 
 const initIndex = (entity) => {
-	const indexName = getNestedValue(config.indexes, entity) || entity;
-	return AlgoliaSearch.initIndex(indexName);
+	const index = config.indexes[entity];
+	return AlgoliaSearch.initIndex(index?.indexName || index);
```
Comment (mateus4k) [inline packages/api/app/Utils/Algolia/core.js:8]: We were just repeating "indexName" the whole time. Instead, it is better to take this property **by default**.

Note: if it is an index that does not exist in the config file, such as a **replica index**, we just ignore the indexName and pass the initial value (_string_) as the parameter value

**Review by alexandreadames — APPROVED** [review]
Sucesso.
