### PR TITLE
Fixes bug in technology showcase

### LINKED ISSUE #1018: Lista de vitrines tecnológicas informa itens não publicados
Na lista de vitrines está trazendo tecnologias que ainda não estão publicadas. 

https://plataformasabia.com/vitrines

Precisa trazer somente itens que estejam com o status PUBLISHED.

image

### PR DESCRIPTION
**Pull request by alexandreadames**
## Summary

Resolves #1018

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

### CODE REVIEW

**Review by luizeboli — DISMISSED** [review]

File: packages/api/app/Controllers/Http/InstitutionController.js [hunk 1]
```diff
@@ -2,17 +2,34 @@
...
+			builder.where('active', true);
+		})
+		.first();
+
+	if (
+		institution.$sideLoaded.technologies_count > 0 ||
+		institution.$sideLoaded.services_count > 0
+	) {
+		await Algolia.saveIndex('institution', institution);
+	}
```
Comment (mateus4k) [inline packages/api/app/Controllers/Http/InstitutionController.js:32]: We don't need it here. Otherwise, we would have to delete or include items in Algolia after create/delete a service. It's better to do as it is now: send **everyone** to Algolia and make this filter in the frontend

```suggestion
	await Algolia.saveIndex('institution', institution);
```

File: packages/api/app/Controllers/Http/InstitutionController.js [hunk 2]
```diff
@@ -79,7 +96,6 @@ class InstitutionController {
 				await institution.logo().associate(logo, trx);
 			}
 			await commit();
-			await saveAlgoliaIndex(institution.id);
```
Comment (mateus4k) [inline packages/api/app/Controllers/Http/InstitutionController.js:82]: Remember to undo this change

File: packages/api/test/functional/institution.spec.js [hunk 3]
```diff
@@ -58,8 +58,6 @@ test('POST /institutions creates a new institution', async ({ client, assert })
 	response.assertStatus(201);
 	assert.equal(institutionJson.responsible, user.id);
 	assert.equal(institutionJson.name, institutionFactory.name);
-	assert.isTrue(AlgoliaSearch.initIndex.called);
-	assert.isTrue(AlgoliaSearch.initIndex().saveObject.called);
```
Comment (mateus4k) [inline packages/api/test/functional/institution.spec.js:62]: The same here ☝️

**Review by mateus4k — CHANGES_REQUESTED** [review]

**Comment by nichollasrennah** [comment]
@alexandreadames como está essa PR?

**Comment by alexandreadames** [comment]
> @alexandreadames como está essa PR?

Nichollas eu mandei pra revisão, tá com @mateus4k

File: packages/api/app/Controllers/Http/InstitutionController.js [hunk 4]
```diff
@@ -2,15 +2,27 @@
...
-		.fetch();
+		.withCount('technologies', (builder) => {
+			builder
+				.where('technologies.status', technologyStatuses.PUBLISHED)
+				.where('active', true);
+		})
+		.withCount('services', (builder) => {
+			builder.where('active', true);
+		})
+		.first();
```
Comment (mateus4k) [inline packages/api/app/Controllers/Http/InstitutionController.js:25]: Boa!

**Review by mateus4k — APPROVED** [review]
