### PR TITLE
Removes special chars from slugify

### LINKED ISSUE #1118: Fix slugify of special chars
### Error:
```json
BadRequestError: Bad Request while resolving /technologies/sistema-de-aquaponia-de-1000l-e-6m%B2-de-area-de-cultivo-5
    at SendStream.error (/plataforma-sabia/api/node_modules/send/index.js:270:31)
    at SendStream.pipe (/plataforma-sabia/api/node_modules/send/index.js:520:10)
    at serveStatic (/plataforma-sabia/api/node_modules/serve-static/index.js:125:12)
    at /plataforma-sabia/api/node_modules/pify/index.js:32:6
    at new Promise (<anonymous>)
    at /plataforma-sabia/api/node_modules/pify/index.js:6:9
    at ret (/plataforma-sabia/api/node_modules/pify/index.js:56:76)
    at Static.handle (/plataforma-sabia/api/node_modules/@adonisjs/framework/src/Static/index.js:46:13)
    at MiddlewareBase._resolveMiddleware (/plataforma-sabia/api/node_modules/@adonisjs/middleware-base/index.js:195:28)
    at Runnable._invoke (/plataforma-sabia/api/node_modules/co-compose/src/Runnable.js:76:42)
    at Runnable.run (/plataforma-sabia/api/node_modules/co-compose/src/Runnable.js:143:17)
    at Server._executeServerMiddleware (/plataforma-sabia/api/node_modules/@adonisjs/framework/src/Server/index.js:80:8)
    at Server.handle (/plataforma-sabia/api/node_modules/@adonisjs/framework/src/Server/index.js:415:10)
    at Server.emit (events.js:375:28)
    at Server.emit (domain.js:470:12)
    at parserOnIncoming (_http_server.js:897:12)
```
### Request:
URL: *GET* /technologies/sistema-de-aquaponia-de-1000l-e-6m%B2-de-area-de-cultivo-5?embed
```json
{"embed":""}
```

### PR DESCRIPTION
**Pull request by alexandreadames**
## Summary

Resolves #1118 

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

### CODE REVIEW

File: packages/api/app/Utils/slugify.js [hunk 1]
```diff
@@ -1,8 +1,19 @@
...
+	textWithoutAccents = text.toLowerCase();
+	textWithoutAccents = textWithoutAccents.replace(new RegExp('[ÁÀÂÃ]', 'gi'), 'a');
+	textWithoutAccents = textWithoutAccents.replace(new RegExp('[ÉÈÊ]', 'gi'), 'e');
+	textWithoutAccents = textWithoutAccents.replace(new RegExp('[ÍÌÎ]', 'gi'), 'i');
+	textWithoutAccents = textWithoutAccents.replace(new RegExp('[ÓÒÔÕ]', 'gi'), 'o');
+	textWithoutAccents = textWithoutAccents.replace(new RegExp('[ÚÙÛ]', 'gi'), 'u');
+	textWithoutAccents = textWithoutAccents.replace(new RegExp('[Ç]', 'gi'), 'c');
+	return textWithoutAccents;
+};
+
```
Comment (mateus4k) [inline packages/api/app/Utils/slugify.js:16]: Esses métodos retornam uma nova string, então, vc pode encadeá-los.

```suggestion
const removeAccents = (text) =>
	text
		.toLowerCase()
		.replace(new RegExp('[ÁÀÂÃ]', 'gi'), 'a')
		.replace(new RegExp('[ÉÈÊ]', 'gi'), 'e')
		.replace(new RegExp('[ÍÌÎ]', 'gi'), 'i')
		.replace(new RegExp('[ÓÒÔÕ]', 'gi'), 'o')
		.replace(new RegExp('[ÚÙÛ]', 'gi'), 'u')
		.replace(new RegExp('[Ç]', 'gi'), 'c');
```

File: packages/api/test/unit/slugify.spec.js [hunk 2]
```diff
@@ -62,6 +62,17 @@ test('add the first suffix when does not have suffix', async ({ assert }) => {
...
 });
 
+test('remove special characters from slug property', async ({ assert }) => {
+	const mySlugWithSpecialCharacters = await createUniqueSlug(
+		new StubModel(),
+		'Technology with+ special %$#(@ characters *6m² and accents áéíóú',
+	);
+	assert.equal(
+		mySlugWithSpecialCharacters,
+		'technology-with-special-characters-6m-and-accents-aeiou',
```
Comment (mateus4k) [inline packages/api/test/unit/slugify.spec.js:72]: O resultado deveria ser um `6m2` ao invés de `6m²`
```suggestion
		'technology-with-special-characters-6m2-and-accents-aeiou',
```

File: packages/api/app/Utils/slugify.js [hunk 3]
```diff
@@ -1,18 +1,10 @@
 const slugify = require('slugify');
 
-const Database = use('Database');
+/** Extends slugify charMap: https://github.com/simov/slugify/blob/master/config/charmap.json */
+slugify.extend({ '²': '2' });
```
Comment (mateus4k) [inline packages/api/app/Utils/slugify.js:4]: Coloca o ¹⁴⁵⁶⁷⁸⁹ aí também :)

File: packages/api/database/migrations/1626211781279_user_city_state_schema.js [hunk 4]
```diff
@@ -52,8 +52,8 @@ class UserCityStateSchema extends Schema {
 	down() {
 		this.alter('users', (table) => {
 			// reverse alternations
-			table.dropForeign(['city_id']).dropColumn('city_id');
-			table.dropForeign(['state_id']).dropColumn('state_id');
+			table.dropColumn('city_id');
```
Comment (mateus4k) [inline packages/api/database/migrations/1626211781279_user_city_state_schema.js:55]: :thinking:

**Review by mateus4k — CHANGES_REQUESTED** [review]
https://github.com/ufersa/plataforma-sabia/pull/1155#discussion_r688184576

**Review by mateus4k — APPROVED** [review]
:100:
